/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DeliveryNode: typeof import('./src/components/DeliveryNode.vue')['default']
    ExpeCard: typeof import('./src/components/ExpeCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NodeLabel: typeof import('./src/components/NodeLabel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecialNode: typeof import('./src/components/SpecialNode.vue')['default']
  }
}
